[connections.snowflake]
account = "VHB12435"   # dash-separated, e.g. "acme-org-prod"
user = "KARINADZIEDZIC"
# choose ONE auth method:
password = "10sierpniaK!!!"    # or:
# private_key_file = "/path/to/key.p8"

role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"